<?php header('Content-Type: application/json'); ?>
[
{"type" : "group", "name" : "Bar Chart"},
"active_bar.js",
"active_stack_bar.js",
"bar.js",
"bar_compare_layout.js",
"bar3d.js",
"cluster_bar3d.js",
"fullstackbar.js",
"fullstackbar3d.js",
"fixed_bar.js",
"fixed_imagebar.js",
"imagebar.js",
"inner_bar.js",
"overlap_bar.js",
"patternbar.js",
"rangebar.js",
"stack_bar.js",
"stack_bar3d.js",

{"type" : "group", "name" : "Column Chart"},
"active_column.js",
"active_stack_column.js",
"column.js",
"column3d.js",
"cluster_column3d.js",
"fixed_column.js",
"fixed_imagecolumn.js",
"fullstack.js",
"fullstackcolumn3d.js",
"fullstackcylinder3d.js",
"cluster_cylinder3d.js",
"imagecolumn.js",
"inner_column.js",
"overlap_column.js",
"patterncolumn.js",
"rangecolumn.js",
"stack_column.js",
"stack_column3d.js",
"cylinder3d.js",
"equalizer.js",
"waterfall.js",
"stack_cylinder3d.js",
{"type" : "group", "name" : "Pie & Donut"},
"pie.js",

"3d_donut.js",
"3d_pie.js",
"active_donut.js",
"active_pie.js",
"donut.js",
{"type" : "group", "name" : "Line Chart"},
"line.js",
"curve_line.js",
"active_line.js",
"range_line.js",
"stack_line.js",
"step_line.js",
"split_line.js",
{"type" : "group", "name" : "Bubble & Scatter Chart"},
"active_scatter.js",
"bubble.js",
"image_scatter.js",
"range_bubble.js",
"range_scatter.js",
"range_scatter_cross.js",
"range_scatter_dragselect.js",
"range_scatter_zoom.js",
"scatter.js",
"scatterpath.js",
"stack_scatter.js",
{"type" : "group", "name" : "Area Chart"},
"area.js",
"curve_area.js",
"split_area.js",
"stack_area.js",
"stack_area2.js",
"stack_curve_area.js",
"stack_step_area.js",
"step_area.js",
{"type" : "group", "name" : "Gauge Chart"},
"gauge.js",
"fill_custom_gauge.js",
"fill_gauge.js",
"full_gauge.js",
"bar_gauge.js",
"circle_gauge.js",
"stack_gauge.js",
{"type" : "group", "name" : "Radar Chart"},
"radar.js",
"circle_radar.js",
{"type" : "group", "name" : "Candle Chart"},
"candlestick.js",
"ohlc.js",
{"type" : "group", "name" : "Map Chart"},
"koreamap_weather.js",
"chart_in_worldmap.js", 
"worldmap1.js", 
"worldmap2.js", 
"worldmap3.js", 
"worldmap4.js", 
"worldmap6.js",

{"type" : "group", "name" : "Dashboard & Mixed Chart"},
"dashboard.js",
"dashboard2.js",
"dashboard3.js",
"mixed1.js",
"mixed2_multi_axis.js",
"mixed3_axis.js",
"mixed3_axis_2.js",
"mixed3_axis_3.js",
"mixed4_linebar.js",
"mixed5.js",
"dashboard4.js"
]